# Generated by Django 4.1.7 on 2023-04-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_remove_profile_firstname_remove_profile_lastname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='CSC 217', max_length=10)),
                ('title', models.TextField(default='Discrete Mathemantics', max_length=50)),
                ('desc', models.TextField(default='', max_length=500)),
            ],
        ),
    ]
