# Generated by Django 4.1.7 on 2023-04-26 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_courses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
    ]
